<template>
  <q-toolbar class="bg-primary text-white q-mt-lg">
    <q-toolbar-title> Table </q-toolbar-title>
  </q-toolbar>
  <q-separator />
  <div class="q-pt-md">
    <div class="q-ma-lg">
      <div class="q-pa-md">
        <div class="q-gutter-y-md">
          <div class="q-mt-sm text-h6">1. 新增 class guide-table</div>
        </div>
      </div>
    </div>

    <q-table
      v-model:pagination="initialPagination"
      :rows="rowData"
      :columns="columnData"
      row-key="index"
      class="guide-table"
      style="height: 500px"
      :loading="loading"
    >
      <template v-slot:body="props">
        <q-tr :props="props">
          <q-td v-for="col in props.cols" :key="col.name" :props="props">
            <template v-if="col.name == 'edit'">
              <q-btn
                size="md"
                dense
                class="guide-btn darken-hover"
                color="primary"
                outline
                icon="edit"
              />
            </template>
            <template v-else-if="col.name == 'copy'">
              <q-btn
                size="md"
                dense
                class="guide-btn darken-hover"
                outline
                color="grey"
                icon="file_copy"
              ></q-btn>
            </template>
            <template v-else>{{ col.value }}</template>
          </q-td>
        </q-tr>
      </template>
      <template v-slot:loading>
        <q-inner-loading showing color="primary" size="42px" />
      </template>
    </q-table>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';

//表格載入中
const loading = ref(false);

//分頁資訊
const initialPagination = ref({
  sortBy: 'desc',
  descending: false,
  page: 1,
  rowsPerPage: 5,
});

interface ColumnData {
  name: string;
  label: string;
  field: string | ((row: unknown) => string | number | boolean);
  required?: boolean;
  align?: 'left' | 'right' | 'center';
  sortable?: boolean;
}

let columnData = ref<ColumnData[]>([
  {
    name: 'edit',
    label: '編輯',
    field: 'edit',
  },
  {
    name: 'copy',
    label: '複製',
    field: 'copy',
  },
  {
    name: 'OrderCode',
    required: true,
    align: 'left',
    sortable: true,
    label: '醫令碼',
    field: 'OrderCode',
  },
  {
    name: 'InsuCode',
    required: true,
    align: 'left',
    sortable: true,
    label: '健保碼',
    field: 'InsuCode',
  },
  {
    name: 'OrderCName',
    required: true,
    align: 'left',
    sortable: true,
    label: '醫令名稱',
    field: 'OrderCName',
  },
  {
    name: 'OrderEName',
    required: true,
    align: 'left',
    sortable: true,
    label: '醫令名稱(英)',
    field: 'OrderEName',
  },
  {
    name: 'TypeCode',
    required: true,
    align: 'left',
    sortable: true,
    label: '醫令類別',
    field: 'TypeCode',
  },
  {
    name: 'InsurancePremium',
    required: true,
    align: 'left',
    sortable: true,
    label: '健',
    field: 'InsurancePremium',
  },
  {
    name: 'NonNHI',
    required: true,
    align: 'left',
    sortable: true,
    label: '自',
    field: 'NonNHI',
  },

  {
    name: 'StartDate',
    required: true,
    align: 'left',
    sortable: true,
    label: '生效起日',
    field: 'StartDate',
  },
  {
    name: 'EndDate',
    required: true,
    align: 'left',
    sortable: true,
    label: '生效迄日',
    field: 'EndDate',
  },
  {
    name: 'IsStop',
    required: true,
    align: 'left',
    sortable: true,
    label: '是否停用',
    field: 'IsStop',
  },
]);
const rowData = ref([
  {
    OrderCode: '00148A',
    InsuCode: '00148A',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130, //手動新增
    NonNHI: 130, //手動新增
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148B',
    InsuCode: '00148B',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148C',
    InsuCode: '00148C',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'N',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148D',
    InsuCode: '00148D',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148E',
    InsuCode: '00148E',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148F',
    InsuCode: '00148F',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148G',
    InsuCode: '00148G',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
  {
    OrderCode: '00148H',
    InsuCode: '00148H',
    OrderEName: '醫令名稱英文',
    OrderCName: '一般門診診察費 - 基層院所門診診',
    ProductName: '產品名稱',
    GenericDrug: '學名',
    TypeCode: '診查費',
    InsurancePremium: 130,
    NonNHI: 130,
    FeeClassNo: '134',
    DefDose: '',
    DefDoseUnit: '',
    DefFrequency: '',
    DefDays: '',
    PackageUnit: '',
    InsuNHIUnit: '',
    MaxDays: '',
    MaxDose: '',
    PackageTranQTY: '',
    ChildLimitDose: '',
    ChildDose: '',
    IsCharge: '',
    IsINSUPay: true,
    IsStock: true,
    DrugElementCode: '',
    ATCCode: '',
    DosageForm: '',
    DrugRouteCode: '',
    IsStop: 'Y',
    StopDate: '',
    StartDate: '087.07.01',
    EndDate: '090.12.31',
    ModifyDate: '',
    ModifyUID: '',
    IsProject: '',
    IsSerialNumber: '',
    IsConsignment: '',
    IsInsuPosition: '',
    IsInsuExtraCost: '',
    IsChildExtraCost: '',
    IsEmergentCost: '',
    OtherExtraCost: '',
    IsVaccine: '',
    VaccineClassNo: '',
    LicenseNo: '',
    SetTempNamingA: true,
    SetTempNamingB: true,
    SetTempNamingC: true,
  },
]);
</script>
<style scoped lang="scss"></style>
